packages:
  - apps/*
  - shared-config/*
  - packages/*

allowBuilds:
  '@swc/core': false
  esbuild: true
  msw: true
  protobufjs: false

# Sentralisert versjonshåndtering - referer med "catalog:" i package.json
catalog:
  '@axe-core/playwright': ^4.12.1
  '@grafana/faro-react': ^2.9.0
  '@grafana/faro-web-sdk': ^2.9.0
  '@navikt/aksel-icons': ^8.16.1
  '@navikt/ds-css': ^8.16.1
  '@navikt/ds-react': ^8.16.1
  '@navikt/ds-tailwind': ^8.16.1
  '@playwright/test': ^1.62.1
  '@tailwindcss/vite': ^4.3.3
  '@tanstack/react-query': ^5.101.4
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.3
  '@types/node': ^26.2.0
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  '@types/react-router-dom': ^5.3.3
  '@vitejs/plugin-react-swc': ^4.3.3
  dayjs: ^1.11.21
  jsdom: ^29.1.1
  msw: ^2.15.0
  playwright: ^1.62.1
  react: ^19.2.8
  react-dom: ^19.2.8
  react-router-dom: ^7.18.2
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  uuid: ^14.0.1
  vite: ^8.2.1
  vitest: ^4.1.10
  zod: ^4.4.3

# Pakker må være 7 dager gamle før de kan installeres (likt som dependabot cooldown)
# Et sikkerhetstiltak i tilfelle en pakke blir komprimittert
minimumReleaseAge: 10080 # 24 x 60 x 7

# Unntak for manuelt oppdaterte pakker innenfor minimumReleaseAge
minimumReleaseAgeExclude:
