name: Setup frontend
description: Steps for setup of the frontend modules

inputs:
  node_auth_token:
    description: Token used to get dekoratoren
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 9.1.4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
