name: Setup frontend
description: Steps for setup of the frontend modules

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 8.15.4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
