apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-deltaker-flate
  namespace: amt
  labels:
    team: amt
spec:
  env:
  - name: CORS_ALLOWED_ORIGINS
    value: "https://www.nav.no,https://mulighetsrommet-admin-flate.intern.nav.no"
  image: {{ image }}
  port: 8080
  liveness:
    path: /amt/amt-deltaker-flate/internal/isAlive
    initialDelay: 10
  readiness:
    path: /amt/amt-deltaker-flate/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /amt/amt-deltaker-flate/internal/metrics
  replicas:
    min: 2
    max: 4
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
  ingresses:
    - "https://www.nav.no/amt/amt-deltaker-flate"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
