apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-deltaker-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  ingresses:
    - https://amt-deltaker-flate.intern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: amt-deltaker-flate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-deltaker-bff
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/deltaker",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-flate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/amt-deltaker-bff",
              "toUrl": "http://amt-deltaker-bff",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
