apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: amt-deltaker-innbyggers-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.10.04_13.21-c31f6e652a0c
  port: 8080
  ingresses:
    - https://amt.intern.dev.nav.no/arbeidsmarkedstiltak
    - https://amt.ansatt.dev.nav.no/arbeidsmarkedstiltak
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    disableAutoScaling: true
    min: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  gcp:
    buckets:
      - name: amt-deltaker-innbyggers-flate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-deltaker-bff
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/arbeidsmarkedstiltak",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-innbyggers-flate-dev"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "proxies": [
            {
              "fromPath": "/pr-[0-9]+/amt-deltaker-bff",
              "toUrl": "http://amt-deltaker-bff",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/amt-deltaker-bff",
              "toUrl": "http://amt-deltaker-bff",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "dev-gcp"
              }
            }
          ]
        }

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
