apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-deltaker-innbyggers-flate-demo
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.02.26_09.22-a08b941e2c0d
  port: 8080
  ingresses:
    - https://amt.ekstern.dev.nav.no/arbeidsmarkedstiltak
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: amt-deltaker-innbyggers-flate-demo
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/arbeidsmarkedstiltak",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-innbyggers-flate-demo"
          },
        }
