apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: amt-deltaker-innbyggers-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.11.05_06.54-7942bce02704
  port: 8080
  ingresses:
    - https://www.nav.no/arbeidsmarkedstiltak
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 500
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  gcp:
    buckets:
      - name: amt-deltaker-innbyggers-flate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-deltaker-bff
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/arbeidsmarkedstiltak",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-innbyggers-flate-prod"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "proxies": [
            {
              "fromPath": "/amt-deltaker-bff",
              "toUrl": "http://amt-deltaker-bff",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "prod-gcp"
              }
            }
          ]
        }

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
