name: Branch Lint and Test
on:
  push:
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
