name: Deploy NAIS poao-frontend
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*-deploy-poao-frontend.yaml
      - apps/**/nais/nais-*.yaml

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: filter
        with:
          filters: |
            innbyggers-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/innbyggers-flate/nais/nais-*.yaml
            nav-veileders-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/nav-veileders-flate/nais/nais-*.yaml
            tiltakskoordinator-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/tiltakskoordinator-flate/nais/nais-*.yaml

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        module_path: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: ./.github/workflows/reusable-deploy-poao-frontend.yaml
    with:
      module_path: ${{ matrix.module_path }}
      prod_deploy_enabled: ${{ matrix.module_path != 'tiltakskoordinator-flate' }}
      targets: ${{'["dev","demo","prod"]'}}
