name: Deploy NAIS poao-frontend
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*-deploy-poao-frontend.yaml
      - apps/**/nais/nais-*.yaml

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            innbyggers-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/innbyggers-flate/nais/nais-*.yaml
            nav-veileders-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/nav-veileders-flate/nais/nais-*.yaml
            tiltakskoordinator-flate: 
              - .github/workflows/*-deploy-poao-frontend.yaml
              - apps/tiltakskoordinator-flate/nais/nais-*.yaml

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        module_path: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: ./.github/workflows/reusable-deploy-poao-frontend.yaml
    with:
      module_path: ${{ matrix.module_path }}
      prod_deploy_enabled: ${{ matrix.module_path != 'tiltakskoordinator-flate' }}
