name: Deploy NAIS poao-frontend to DEMO for innbyggers-flate
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/.github/workflows/innbyggers-flate-deploy-poao-frontend-demo.yaml"
      - apps/innbyggers-flate/nais/nais-demo.yaml

jobs:
  deploy-demo:
    name: Deploy poao-frontend to DEMO - innbyggers-flate
    runs-on: ubuntu-latest
    permissions:
      id-token: "write" # Needed for `nais/deploy/actions/deploy`
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/innbyggers-flate/nais/nais-demo.yaml
          PRINT_PAYLOAD: true
