name: Deploy NAIS poao-frontend to PROD for innbyggers-flate
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/innbyggers-flate-deploy-poao-frontend-prod.yaml'
      - apps/innbyggers-flate/nais/nais-prod.yaml
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy poao-frontend to PROD - innbyggers-flate
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/innbyggers-flate/nais/nais-prod.yaml
          PRINT_PAYLOAD: true
