name: Update GitHub Pages for nav-veileders-flate
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-deltaker-flate/actions/workflows/gh-pages.yaml
  paths:
      - .github/workflows/nav-veileders-flate-gh-pages.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - apps/nav-veileders-flate/**
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:

  update-gh-pages:
    permissions:
      contents: "read"
      id-token: "write"
      pages: "write"

    concurrency:
      group: "pages"
      cancel-in-progress: true

    name: Update GitHub pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build mock application
        run: pnpm build:gh-pages --base amt-deltaker-flate
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload build repository
          path: apps/nav-veileders-flate/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
