name: Rydd applikasjon for PR
on:
  pull_request:
    paths-ignore:
      - .github/workflows/innbyggers-flate-deploy.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-demo.yaml
      - .github/workflows/innbyggers-flate-pr-deploy.yaml
      - .github/workflows/innbyggers-flate-pr-comment-link.yaml
      - .github/workflows/innbyggers-flate-pr-cleanup.yaml
      - apps/innbyggers-flate/**
      - .github/workflows/tiltakskoordinator-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/tiltakskoordinator-flate-deploy.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-cleanup.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-comment-link.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-deploy.yaml
      - apps/tiltakskoordinator-flate/**
    branches:
      - main
    types:
      - closed
jobs:
  cleanup-pr-nav-veileders-flate:
    if: github.event.pull_request.head.repo.fork != true
    name: Rydd applikasjon for PR
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-deltaker-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Delete files on GCS
        run: gsutil rm -r gs://amt-deltaker-flate-dev-v2/pr-${{ github.event.number }}
