name: Update GitHub Pages for nav-veileders-flate
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-deltaker-flate/actions/workflows/gh-pages.yaml
  push:
    paths:
      - .github/actions/**
      - .github/workflows/nav-veileders-flate-gh-pages.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - apps/nav-veileders-flate/**
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:

  update-gh-pages:
    permissions:
      contents: "read"
      id-token: "write"
      pages: "write"

    concurrency:
      group: "pages"
      cancel-in-progress: true

    name: Update GitHub pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: "https://npm.pkg.github.com"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turborepo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turborepo-${{ github.ref_name }}-
            turborepo-
      - name: Build mock application
        run: pnpm build:gh-pages --base amt-deltaker-flate
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload build repository
          path: apps/nav-veileders-flate/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
