name: Opprett lenke til test applikasjon nav-veileders-flate for PR
on:
  pull_request:
    paths-ignore:
      - .github/workflows/innbyggers-flate-deploy.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-demo.yaml
      - .github/workflows/innbyggers-flate-pr-deploy.yaml
      - .github/workflows/innbyggers-flate-pr-comment-link.yaml
      - .github/workflows/innbyggers-flate-pr-cleanup.yaml
      - apps/innbyggers-flate/**
      - .github/workflows/tiltakskoordinator-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/tiltakskoordinator-flate-deploy.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-cleanup.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-comment-link.yaml
      - .github/workflows/tiltakskoordinator-flate-pr-deploy.yaml
      - apps/tiltakskoordinator-flate/**
    branches:
      - main
    types:
      - opened
jobs:
  create-link-to-app:
    permissions:
      pull-requests: 'write'
    name: Opprett lenke til test applikasjon for PR
    runs-on: ubuntu-latest
    steps:
      - name: Opprett lenke til test applikasjon nav-veileders-flate for PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            URLer for testing av nav-veileders-flate:
              https://amt-deltaker-flate.intern.dev.nav.no/pr-${{ github.event.number }}/index.html
              https://amt-deltaker-flate.ansatt.dev.nav.no/pr-${{ github.event.number }}/index.html
