name: Branch Lint and Test for nav-veileders-flate
on:
  push:
    paths:
      - .github/workflows/nav-veileders-flate-branch-test.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - apps/nav-veileders-flate/**
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Lint
        run: pnpm lint --filter=nav-veileders-flate
      - name: Run tests
        run: pnpm test:no-watch --filter=nav-veileders-flate
      - name: Build
        run: pnpm build --filter=nav-veileders-flate
