name: Branch Lint and Test
on:
  push:
    paths:
      - .github/actions/**
      - .github/workflows/nav-veileders-flate-branch-test.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - apps/nav-veileders-flate/**
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Lint
        run: pnpm lint --filter=nav-veileders-flate
      - name: Run tests
        run: pnpm test:no-watch --filter=nav-veileders-flate
      - name: Build
        run: pnpm build --filter=nav-veileders-flate
