name: Deploy Pull Request Branch
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-deltaker-flate/actions/workflows/deploy.yaml
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  deploy-pull-request-branch:
    if: github.event.pull_request.head.repo.fork != true
    name: Deploy Pull Request Branch
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.13.1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build Pull Request Application
        run: pnpm build:pull-request --base=/pr-${{ github.event.number }}/
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-deltaker-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-deltaker-flate-dev/pr-${{ github.event.number }}
