name: Reusable Deploy NAIS poao-frontend
on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

      prod_deploy_enabled:
        required: false
        type: boolean
        default: true

      targets:
        required: false
        type: string
        default: '["dev","prod"]'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJSON(inputs.targets) }}
    name: Deploy poao-frontend ${{ matrix.target }} - ${{ inputs.module_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Deploy application
        if: |
          matrix.target == 'dev' ||
          (matrix.target == 'demo' && github.ref == 'refs/heads/main') ||
          (matrix.target == 'prod' && github.ref == 'refs/heads/main' && inputs.prod_deploy_enabled == true)
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: ${{ matrix.target == 'prod' && 'prod-gcp' || 'dev-gcp' }}
          RESOURCE: apps/${{ inputs.module_path }}/nais/nais-${{ matrix.target }}.yaml
          PRINT_PAYLOAD: true
