name: Deploy tiltakskoordinator-flate
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-deltaker-flate/actions/workflows/deploy.yaml
  push:
    paths-ignore:
      - .github/workflows/innbyggers-flate-deploy.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/innbyggers-flate-deploy-poao-frontend-demo.yaml
      - .github/workflows/innbyggers-flate-pr-deploy.yaml
      - .github/workflows/innbyggers-flate-pr-comment-link.yaml
      - .github/workflows/innbyggers-flate-pr-cleanup.yaml
      - apps/innbyggers-flate/**
      - .github/workflows/nav-veileders-flate-deploy.yaml
      - .github/workflows/nav-veileders-flate-pr-deploy.yaml
      - .github/workflows/nav-veileders-flate-pr-comment-link.yaml
      - .github/workflows/nav-veileders-flate-pr-cleanup.yaml
      - .github/workflows/nav-veileders-flate-deploy-poao-frontend-dev.yaml
      - .github/workflows/nav-veileders-flate-deploy-poao-frontend-prod.yaml
      - apps/nav-veileders-flate/**
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  playwright-version:
    name: Get playwright version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/tiltakskoordinator-flate
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v5
      - id: get-version
        run: echo "version=$(cat package.json | jq -r '.devDependencies.playwright' | sed -e 's/^[\^\~]//')" >> "$GITHUB_OUTPUT"

  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    needs: playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.version }}-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          node_auth_token: ${{ secrets.READER_TOKEN }}
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test:no-watch
      - name: Run playwright tests
        run: pnpm playwright --filter=tiltakskoordinator-flate

  deploy-dev-tiltakskoordinator-flate:
    name: Deploy tiltakskoordinator-flate to DEV
    runs-on: ubuntu-latest
    needs: test-and-lint
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          node_auth_token: ${{ secrets.READER_TOKEN }}
      - name: Build
        run: pnpm build:dev --filter=tiltakskoordinator-flate
      - name: Upload files to CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: amt
          source: apps/tiltakskoordinator-flate/build
          destination: amt-tiltakskoordinator-flate-dev
          no_cache_paths: amt-tiltakskoordinator-flate-dev/build/asset-manifest.json
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}

  deploy-demo-tiltakskoordinator-flate:
    if: github.ref == 'refs/heads/main'
    name: Deploy tiltakskoordinator-flate DEMO
    runs-on: ubuntu-latest
    needs: test-and-lint
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          node_auth_token: ${{ secrets.READER_TOKEN }}
      - name: Build
        run: pnpm build:demo --filter=tiltakskoordinator-flate
      - uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: amt
          source: apps/tiltakskoordinator-flate/build
          source_keep_parent_name: false
          destination: amt-tiltakskoordinator-flate/dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-prod-tiltakskoordinator-flate:
    if: github.ref == 'refs/heads/main'
    name: Deploy tiltakskoordinator-flate to PROD
    runs-on: ubuntu-latest
    needs: test-and-lint
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          node_auth_token: ${{ secrets.READER_TOKEN }}
      - name: Build
        run: pnpm build --filter=tiltakskoordinator-flate
      - name: Upload files to CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: amt
          source: apps/tiltakskoordinator-flate/build
          destination: amt-tiltakskoordinator-flate-prod
          no_cache_paths: amt-tiltakskoordinator-flate-prod/build/asset-manifest.json
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
