apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: amt-deltaker-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.05.06_08.20-c92409cd4d8b
  port: 8080
  ingresses:
    - https://www.nav.no/amt/deltaker
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
  gcp:
    buckets:
      - name: amt-deltaker-flate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-deltaker-bff
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-flate-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/amt-deltaker-bff", "toUrl": "http://amt-deltaker-bff",
              "toApp": { "name": "amt-deltaker-bff", "namespace": "amt", "cluster": "prod-gcp" }
            }
          ]
        }
