apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: amt-deltaker-flate-demo
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2026.05.04_08.28-44f053d6a1a4
  port: 8080
  ingresses:
    - https://amt-deltaker-nav-veileders-flate-demo.ekstern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    disableAutoScaling: true
    min: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
        - /amt-deltaker-bff/**
  gcp:
    buckets:
      - name: amt-deltaker-nav-veileders-flate-demo #demo app
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-deltaker-bff
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-deltaker-nav-veileders-flate-demo"
          }
        }

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
