apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: amt-veileder-flate-demo
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2026.06.23_07.52-12f3e7193bdf
  port: 8080
  ingresses:
    - https://amt-veileder-flate-demo.ekstern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    disableAutoScaling: true
    min: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  gcp:
    buckets:
      - name: amt-veileder-flate-demo #demo app
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "nais-cdn-nav-amt-a889",
            "bucketContextPath": "amt/amt-veileder-flate-demo"
          }
        }

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
